services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all # 1 # alternatively, use `count: all` for all GPUs
              capabilities: [gpu]
volumes:
  ollama:
