services:
  tailscale-ollama:
    image: tailscale/tailscale:latest
    container_name: ts-ollama
    hostname: ${hostname}
    environment:
      - TS_AUTHKEY=${ts_auth_key}
      #      - TS_EXTRA_ARGS=
      - TS_AUTH_ONCE=true
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
    volumes:
      - tailscale_ollama:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    depends_on:
      - tailscale-ollama
    network_mode: service:tailscale-ollama
    # ports:
    #   - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all # 1 # alternatively, use `count: all` for all GPUs
              capabilities: [gpu]
volumes:
  ollama:
  tailscale_ollama:
